openapi: 3.0.2

GeneralError:
  description: General Error. Something went wrong, e.g. MySQL/Neo4j database request.
  content:
    application/json:
      schema:
        properties:
          message:
            type: string
          originalErr:
            anyOf:
              - type: string
              - type: object

LoginToken:
  description: Valid access token.
  content:
    application/json:
      schema:
        properties:
          token:
            type: string
          expires:
            type: integer
          user:
            type: object
            properties:
              email:
                type: string
              name:
                type: string
              password:
                type: string

InvalidCredentials:
  description: The user credentials are either missing or invalid.
  content:
    application/json:
      schema:
        properties:
          message:
            type: string
      example:
        summary: Example response for invalid credentials.
        value:
          message: Invalid credentials #6

NoPermission:
  description: The user is not allowed to execute this operation.
  content:
    application/json:
      schema:
        properties:
          message:
            type: string
          error:
            type: string

Project:
  description: Project details.
  content:
    application/json:
      schema:
        $ref: schemas.yaml#/Project
