openapi: 3.0.2

GeneralAbort:
  type: object
  properties:
    message:
      type: string

Credentials:
  properties:
    email:
      type: string
    password:
      type: string
      format: password

Project:
  description: Project details
  type: object
  properties:
    pid:
      type: integer
      description: ID in MySQL database table
    proj:
      type: string
      description: Project ID (should be renamed to `id`)
    name:
      type: string
      description: Title of the project
    description:
      type: string
      description: Short description
    role:
      type: string
      description: User's role on this project
  example:
    pid: 1
    proj: Proj_BJ24xXaAW
    name: First project
    description: This is my first project
    role: superadmin

